import { Todo } from './todo.model';

export const TODOS: Todo[] = [
  { id: 1, title: 'Buy groceries', completed: false },
  { id: 2, title: 'Walk the dog', completed: true },
  { id: 3, title: 'Finish TypeScript project', completed: false },
  { id: 4, title: 'Call mom', completed: true },
  { id: 5, title: 'Clean the house', completed: false },
  { id: 6, title: 'Prepare dinner', completed: false },
  { id: 7, title: 'Read a book', completed: true },
  { id: 8, title: 'Pay bills', completed: false },
  { id: 9, title: 'Schedule a meeting', completed: true },
  { id: 10, title: 'Exercise for 30 minutes', completed: false },
  { id: 11, title: 'Write a blog post', completed: false },
  { id: 12, title: 'Plan weekend trip', completed: true },
  { id: 13, title: 'Organize workspace', completed: false },
  { id: 14, title: 'Respond to emails', completed: true },
  { id: 15, title: 'Fix the leaky faucet', completed: false },
  { id: 16, title: 'Watch a tutorial', completed: true },
  { id: 17, title: 'Update resume', completed: false },
  { id: 18, title: 'Meditate for 10 minutes', completed: true },
  { id: 19, title: 'Research new tech trends', completed: false },
  { id: 20, title: 'Prepare presentation slides', completed: true },
  { id: 21, title: 'Water the plants', completed: false },
  { id: 22, title: 'Plan weekly meals', completed: true },
  { id: 23, title: 'Backup important files', completed: false },
  { id: 24, title: 'Learn a new recipe', completed: true },
  { id: 25, title: 'Declutter the closet', completed: false },
];
